---
- hosts: ubuntuhosts
  tasks:
    - name: Print OS family to site
      shell: echo "The family is {{ansible_os_family}}" > /home/{{ansible_user_id}}/family.txt
    - name: Print default machine NIC name to console
      debug: msg={{ansible_default_ipv4.interface}}
    - name: Register ls results variable
      command: "ls"
      register: dirs
    - name: Print dirs variable from last step to console
      debug:
        msg: "{{dirs}}"