---
- name: Demo ansible loops
  hosts: ubuntu
  become: true
  tasks:
    - name: Create a file
      shell: echo 'Begin file' > /home/ubuntu/loops.txt
    - name: install packages
      shell: echo "{{item}}" >> /home/ubuntu/loops.txt
      with_items:
        - vim
        - nano
        - python